_wandb:
    value:
        cli_version: 0.23.1
        e:
            g15ff7776a3pdpah9tla4e92ai3a3b4d:
                codePath: learning/notebooks/train_panda_ppo.py
                codePathLocal: learning/notebooks/train_panda_ppo.py
                email: weissma6@students.zhaw.ch
                executable: /Users/matthiasweiss/miniconda3/envs/mujoco/bin/python
                git:
                    commit: 0fd8c0e44c30a322649f03667ba4ebe05d76f367
                    remote: https://github.com/weissma6/my_mujoco_playground.git
                host: MBPvonMatthias.galaxus.box
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/matthiasweiss/Desktop/ZHAW/MSE/3_VT1_Model Based RL/My_Mujoco/my_mujoco_playground/learning/notebooks/train_panda_ppo.py
                python: CPython 3.10.19
                root: /Users/matthiasweiss/Desktop/ZHAW/MSE/3_VT1_Model Based RL/My_Mujoco/my_mujoco_playground
                startedAt: "2025-12-05T11:56:38.043293Z"
                writerId: g15ff7776a3pdpah9tla4e92ai3a3b4d
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
algo:
    value: PPO
env_name:
    value: PandaPickCubeOrientation
ppo/action_repeat:
    value: 1
ppo/batch_size:
    value: 512
ppo/discounting:
    value: 0.97
ppo/entropy_cost:
    value: 0.02
ppo/episode_length:
    value: 150
ppo/learning_rate:
    value: 0.001
ppo/normalize_observations:
    value: true
ppo/num_envs:
    value: 2048
ppo/num_evals:
    value: 4
ppo/num_minibatches:
    value: 32
ppo/num_resets_per_eval:
    value: 10
ppo/num_timesteps:
    value: 20000000
ppo/num_updates_per_batch:
    value: 8
ppo/reward_scaling:
    value: 1
ppo/unroll_length:
    value: 10
seed:
    value: 1131532716
