"""Generate the DR-ladder + LOO sweep JSONL, velocity-obs variant.

Same 10 configs as `gen_dr_ladder.py` (L0_none .. L5_full_obs, LOO_no_pos ..
LOO_no_env) -- imports its `_CONFIGS` directly so the DR-cluster -> config-key
mapping has ONE source of truth and cannot drift between the two sweeps. See
that script's docstring for the full cluster spec and the vault's
"Plan - Sim-to-Real Gap Protocol" for the research design.

What's DIFFERENT here, on every line:
  - `obs_include_velocity: true` -- appends arm joint velocity (6D) + finger
    velocity (1D) to the obs (26D -> 33D). See the vault's
    "Plan - Add Velocity": a single L1_pos test at this setting (action_scale
    =0.04, position DR only) converged within ~10M steps, well under the
    ladder's usual ~32M-step budget. This sweep tests whether that holds
    across the whole dose-response ladder, or was specific to the easiest
    rung.
  - `action_scale: 0.04` (arm). Set explicitly on every line so nothing is
    inherited from a drifting env default -- the same reasoning
    gen_dr_ladder.py already applies to episode_length.

    CORRECTION (2026-07-26): an earlier version of this docstring claimed the
    ORIGINAL ladder trained at 0.04 "per their metadata.json". That is wrong
    and it is what broke the first real-robot campaign. UR3Pick_dr_ladder.jsonl
    sets NO action_scale, so those 30 runs inherited the env default, which
    commit 1636c98 (2026-07-15) had set to 0.015 -- two days before the ladder
    launched at b170af5. The 0.04 in their metadata.json is the hardcoded
    fallback in policy_downloader.py, written whenever the run config carries
    no action_scale. Deploying those policies at 0.04 ran them at 2.67x their
    trained gain. Only a value that also appears in env_overrides is real.

  - `gripper_action_scale: 0.01` (gripper, decoupled from the arm). The finger
    range is [0, 0.025] m, so one full-magnitude action step travels 40% of the
    stroke at 0.01, 80% at 0.02, and 160% at 0.04. The env default of 0.02 is
    already near bang-bang -- its own comment justifies the setting with
    ">=2.5 steps at 0.01", i.e. the rationale was written for 0.01 and the
    value was later doubled without updating it. 0.01 restores that intent.
    This matters more now that velocity is observed: sim's finger qvel stalls
    to zero when the fingers close on the cube, while the real robot's channel
    is a finite difference of a tau=0.1 low-passed COMMAND that never stalls.
    A saturated gripper turns the sim channel into a square wave and maximises
    that mismatch exactly at grasp -- the observed failure mode ("gripper looks
    snappy/jerky, box dropped several times before an eventual grasp").

run_id / wandb_tags get a "_vel" / "velocity" marker so these runs are never
confused with the original (no-velocity) ladder in W&B or in
gap_protocol_policy_map.json.

episode_length=400 is inherited unchanged from gen_dr_ladder.py's _CONFIGS
loop below (same reasoning: ur3_pick.default_config()'s 250 is stale).
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))

from batch_runs.sweeps.gen_dr_ladder import (  # noqa: E402
    _CONFIGS,
    EPISODE_LENGTH,
    WANDB_PROJECT,
)

ACTION_SCALE = 0.04
# Decoupled gripper scale. See the docstring: 0.01 => ~2.5 steps for the full
# 0.025 m open->close travel, restoring the env comment's stated design intent
# (the 0.02 default closes in ~1.25 steps, i.e. effectively bang-bang).
GRIPPER_ACTION_SCALE = 0.01

_HEADER = f"""\
# DR-ladder + LOO sweep, VELOCITY-OBS variant -- "Plan - Add Velocity"
# (VT2-SimToReal-Robotics). Generated by
# batch_runs/sweeps/gen_dr_ladder_velocity.py -- DO NOT hand-edit; regenerate
# instead. Same {len(_CONFIGS)} configs as gen_dr_ladder.py (imported directly,
# not re-specified -- single source of truth for the DR cluster mapping).
#
# Differs from the original ladder on every line: obs_include_velocity=true
# (26D obs -> 33D: + arm qvel(6) + finger qvel(1)), action_scale={ACTION_SCALE}
# (arm) and gripper_action_scale={GRIPPER_ACTION_SCALE} (decoupled). Both are
# set EXPLICITLY so they land in the run config -> env_overrides -> the
# policy's metadata.json, which is the only way a deploy-time check can tell a
# real trained value from policy_downloader.py's hardcoded 0.04 fallback.
# See the module docstring for why that distinction broke the first real
# campaign, and for the 0.025 m finger-stroke arithmetic behind 0.01.
#
# {len(_CONFIGS)} configs x N seeds. Comment/blank lines are skipped by the
# runner and do NOT count toward the 1-based SLURM_ARRAY_TASK_ID.
"""


def build_lines(seeds, version=None):
    lines = [_HEADER]
    version_tag = [version] if version else []
    version_suffix = f"_{version}" if version else ""
    for config_id, overrides, tags in _CONFIGS:
        for seed in seeds:
            entry = {
                "env_name": "UR3Pick",
                "seed": int(seed),
                # config_id unchanged by `version`, same reasoning as
                # gen_dr_ladder.py's build_lines -- only run_id/tags carry it.
                "run_id": f"{config_id}_vel{version_suffix}_s{seed}",
                "wandb_project": WANDB_PROJECT,
                "video_every_evals": 6,
                "render_every": 1,
                "episode_length": EPISODE_LENGTH,
                "action_scale": ACTION_SCALE,
                "gripper_action_scale": GRIPPER_ACTION_SCALE,
                "obs_include_velocity": True,
                **overrides,
                "wandb_tags": [
                    *tags,
                    "velocity",
                    f"as{ACTION_SCALE}",
                    f"gas{GRIPPER_ACTION_SCALE}",
                    f"s{seed}",
                    *version_tag,
                ],
            }
            lines.append(json.dumps(entry))
    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--out",
        default=os.path.join(
            os.path.dirname(__file__), "UR3Pick_dr_ladder_velocity.jsonl"
        ),
    )
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2])
    ap.add_argument(
        "--force", action="store_true", help="overwrite an existing file"
    )
    ap.add_argument(
        "--version", default=None,
        help="tag appended to run_id/wandb_tags (e.g. 'v2'), mirroring "
             "gen_dr_ladder.py's --version. config_id is left unchanged.",
    )
    args = ap.parse_args()

    if os.path.exists(args.out) and not args.force:
        raise SystemExit(
            f"{args.out} already exists; pass --force to overwrite "
            f"(the file should be regenerated from this script, not hand-edited)"
        )

    lines = build_lines(args.seeds, version=args.version)
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    n_runs = len(_CONFIGS) * len(args.seeds)
    print(f"Wrote {n_runs} runs ({len(_CONFIGS)} configs x {len(args.seeds)} "
          f"seeds) to {args.out}")
    # D21 (2026-07-29): this module imports _CONFIGS from gen_dr_ladder.py, so
    # cutting that ladder to 5 configs cuts this velocity ladder with it. The
    # assertion is kept (it is a real drift guard) and updated to the new set.
    assert {c for c, _, _ in _CONFIGS} == {
        "L0_none", "L1_pos", "L2_pos_cube", "L3_pos_cube_robot", "L4_full",
    }, "config set drifted from gen_dr_ladder.py's D21 5-config ladder -- investigate"


if __name__ == "__main__":
    main()
