#!/usr/bin/env python3
"""Sweep A: anchor control + budget. Three budgets x two seeds = six runs.

Plan: "20260904_Sweep A – Anchor control + budget" (campaign "00 Campaign –
Sweeps From What Worked", Wave 1 row 1).

QUESTION: does the defence PPO bundle (Snappy2_as04_ar70_g01 configuration)
still reproduce success 0.6–0.68 on the campaign base commit 38c8372, and does
2–3x budget lift the plateau (Tier B question from 2026-08-14 plan, never run)?

DESIGN: 3 budgets x 2 seeds = 6 runs. num_evals scales with budget
(20/40/60) so solve_budget gives nts=8 for all three -- every run evaluates
once per 1,310,720 steps, identical eval cadence, overlayable curves.
lifter_tilt_max pinned to 0.05 (env default at defence commit a200d41; base
commit 38c8372 defaults to 0.12). Everything else is exactly the
Snappy2_as04_ar70_g01 line via gen_snappy2.build_entry().

COMPARISON ROWS: Snappy2_as04_ar70_g01_s0 (0.586) / _s1 (0.656),
RewardGate_g01_s1 (0.680).
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_satsweep as gs        # noqa: E402
import gen_rewardgate as rg      # noqa: E402
import gen_snappy2 as s2         # noqa: E402

BUDGETS = [24_000_000, 48_000_000, 72_000_000]
SEEDS = [0, 1]
DEFENCE_CELL = (0.04, -0.70)
LIFTER_TILT_MAX = 0.05
RUN_PREFIX = "SweepA_anchor"

assert DEFENCE_CELL in s2.cells(), (
    f"DEFENCE_CELL {DEFENCE_CELL} not found in gen_snappy2.cells(); "
    f"the Snappy2 grid may have changed")


def budget_tag(budget):
    return f"b{budget // 1_000_000}M"


def num_evals_for(budget):
    assert budget % rg.NUM_TIMESTEPS == 0, (
        f"budget {budget} is not a multiple of rg.NUM_TIMESTEPS "
        f"{rg.NUM_TIMESTEPS}")
    return rg.NUM_EVALS * budget // rg.NUM_TIMESTEPS


def run_id(budget, seed):
    return f"{RUN_PREFIX}_{budget_tag(budget)}_s{seed}"


def wandb_tags(budget, seed):
    return ["sweepA", "anchor", budget_tag(budget), f"s{seed}",
            f"anchor{rg.ANCHOR_CELL}"]


def build_entry(budget, seed, shared):
    entry = s2.build_entry(DEFENCE_CELL[0], DEFENCE_CELL[1], seed, shared,
                           budget, num_evals_for(budget))
    entry["run_id"] = run_id(budget, seed)
    entry["wandb_tags"] = wandb_tags(budget, seed)
    entry["lifter_tilt_max"] = float(LIFTER_TILT_MAX)
    return entry


def build_lines(seeds=SEEDS):
    shared = gs.load_target_config()
    assert shared.get("action_scale") == DEFENCE_CELL[0], (
        f"target_config_satsweep.json has action_scale="
        f"{shared.get('action_scale')}, expected {DEFENCE_CELL[0]}")
    assert "action_rate" not in shared, (
        "target_config_satsweep.json now pins action_rate; "
        "the defence runs were trained at the env default")

    totals = {b: gs.solve_budget(b, num_evals_for(b)) for b in BUDGETS}
    nts_values = [nts for nts, _ in totals.values()]
    assert len(set(nts_values)) == 1, (
        f"nts values not identical across budgets: {nts_values}")

    pose_level, pose_n, pose_sha = gs.init_pose_library_fingerprint()
    n_runs = len(BUDGETS) * len(seeds)

    header = (
        f"# Sweep A: anchor control + budget. Generated by\n"
        f"# batch_runs/sweeps/gen_sweep_anchor_budget.py -- DO NOT hand-edit; "
        f"regenerate.\n"
        f"# Plan: '20260904_Sweep A - Anchor control + budget' (campaign "
        f"'00 Campaign - Sweeps From What Worked', Wave 1 row 1).\n"
        f"#\n"
        f"# QUESTION: does the defence PPO bundle (Snappy2_as04_ar70_g01\n"
        f"# configuration) still reproduce success 0.6-0.68 on the campaign\n"
        f"# base commit 38c8372, and does 2-3x budget lift the plateau (Tier B\n"
        f"# question from 2026-08-14 plan, never run)?\n"
        f"#\n"
        f"# CELLS (budget -> num_evals -> nts -> actual steps):\n"
    )

    for b in BUDGETS:
        nts, total = totals[b]
        ne = num_evals_for(b)
        header += (
            f"#   {budget_tag(b)}: num_timesteps={b} num_evals={ne} nts={nts} "
            f"-> ACTUAL TOTAL_STEPS={total}\n"
        )

    e_per_step = gs.env_step_per_training_step()
    nts, _ = totals[BUDGETS[0]]
    total_steps_per_eval = nts * e_per_step
    header += (
        f"# env_step_per_training_step={e_per_step}; nts identical across "
        f"budgets -> one eval every {total_steps_per_eval} steps (same cadence "
        f"as the 24M/20-eval defence run).\n"
        f"#\n"
        f"# lifter_tilt_max is pinned to 0.05: env default at defence commit\n"
        f"# a200d41; base commit 38c8372 defaults to 0.12. Pinned explicitly\n"
        f"# so the sweep rows are directly comparable to the defence baseline.\n"
        f"#\n"
        f"# COMPARE AGAINST: Snappy2_as04_ar70_g01_s0 (0.586), "
        f"Snappy2_as04_ar70_g01_s1 (0.656), RewardGate_g01_s1 (0.680).\n"
        f"#\n"
        f"# FROZEN: {rg.GATE_BOX_KEY}={s2.GATE_BOX}, "
        f"{rg.GATE_ALIGN_KEY}={s2.GATE_ALIGN} (gating winner {s2.GATE_CELL});\n"
        f"#   action_scale={DEFENCE_CELL[0]:g} action_rate={DEFENCE_CELL[1]:g} "
        f"gripper_action_scale={s2.GRIPPER_ACTION_SCALE:g};\n"
        f"#   PPO at Tier A winner {rg.ANCHOR_CELL}. Every line is the "
        f"Snappy2_as04_ar70_g01 line via gen_snappy2.build_entry.\n"
        f"#\n"
        f"# {len(BUDGETS)} budgets x {len(seeds)} seed(s) = {n_runs} runs. "
        f"Comment/blank\n"
        f"# lines are skipped by run_one_ur3.py::load_config and do NOT "
        f"consume a\n"
        f"# SLURM array index: set --array=1-{n_runs}%4.\n"
        f"#\n"
        f"# INIT-POSE LIBRARY: level={pose_level!r} n_poses={pose_n} "
        f"sha256={pose_sha}\n"
        f"# MUST match the runs these are compared against."
    )

    lines = [header]
    for b in BUDGETS:
        for seed in seeds:
            lines.append(json.dumps(build_entry(b, seed, shared)))
    return lines, totals


def check_lines(path, expected_n, seeds):
    rows = [json.loads(l) for l in open(path, encoding="utf-8")
            if l.strip() and not l.lstrip().startswith("#")]
    assert len(rows) == expected_n, (
        f"{len(rows)} data lines, expected {expected_n}")

    ids = [r["run_id"] for r in rows]
    assert len(set(ids)) == len(ids), (
        f"duplicate run_id(s): {[x for x in ids if ids.count(x) > 1]}")

    allowed_stray = gs.REWARD_KEYS - {"action_rate"}
    seen = set()

    for r in rows:
        rid = r["run_id"]
        assert not (allowed_stray & set(r)), (
            f"{rid}: stray reward key(s): {sorted(allowed_stray & set(r))}")

        b = r["num_timesteps"]
        assert b in BUDGETS, (
            f"{rid}: num_timesteps {b} not in BUDGETS")
        assert r["num_evals"] == num_evals_for(b), (
            f"{rid}: num_evals {r['num_evals']} != "
            f"num_evals_for({b}) = {num_evals_for(b)}")
        assert rid == run_id(b, r["seed"]), (
            f"{rid}: run_id disagrees with budget {b} and seed "
            f"{r['seed']}")
        assert r["wandb_tags"] == wandb_tags(b, r["seed"]), (
            f"{rid}: wandb_tags mismatch")
        assert r["lifter_tilt_max"] == LIFTER_TILT_MAX, (
            f"{rid}: lifter_tilt_max {r['lifter_tilt_max']} != "
            f"{LIFTER_TILT_MAX}")
        assert r["box_z_rot_range"] == 6.283185307179586, rid
        assert r["episode_length"] == 400, rid
        assert r["obs_include_velocity"] is True, rid
        assert r["num_resets_per_eval"] == gs.NUM_RESETS_PER_EVAL, rid
        assert r["video_every_evals"] == rg.VIDEO_EVERY_EVALS, rid
        assert r["action_scale"] == DEFENCE_CELL[0], rid
        assert r["action_rate"] == DEFENCE_CELL[1], rid
        assert r["gripper_action_scale"] == s2.GRIPPER_ACTION_SCALE, rid
        assert r[rg.GATE_BOX_KEY] is s2.GATE_BOX, rid
        assert r[rg.GATE_ALIGN_KEY] is s2.GATE_ALIGN, rid
        assert r["entropy_cost"] == rg.ANCHOR["entropy_cost"], rid
        assert r["learning_rate"] == rg.ANCHOR["learning_rate"], rid
        assert r["reward_scaling"] == rg.ANCHOR["reward_scaling"], rid
        nf = r["network_factory"]
        assert tuple(nf["policy_hidden_layer_sizes"]) == \
            rg.ANCHOR["policy_hidden_layer_sizes"], rid
        assert tuple(nf["value_hidden_layer_sizes"]) == \
            gs.VALUE_HIDDEN_LAYER_SIZES, rid
        assert "num_eval_envs" not in r, rid

        seen.add((b, r["seed"]))

    assert seen == {(b, s) for b in BUDGETS for s in seeds}, (
        f"missing or extra (budget, seed) pairs: {sorted(seen)}")

    varying = {"seed", "run_id", "wandb_tags", "num_timesteps", "num_evals"}
    base = {k: v for k, v in rows[0].items() if k not in varying}
    for r in rows[1:]:
        other = {k: v for k, v in r.items() if k not in varying}
        assert other == base, (
            f"{r['run_id']} differs from {rows[0]['run_id']} outside the "
            f"varying keys: "
            f"{{{', '.join(f'{k}: ({base.get(k)}, {other.get(k)})' for k in set(base) | set(other) if base.get(k) != other.get(k))}}}")

    return rows


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1])
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if os.path.exists(args.out) and not args.force:
        raise SystemExit(
            f"{args.out} already exists; pass --force to overwrite (this file "
            f"is generated, not hand-edited)")

    lines, totals = build_lines(args.seeds)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    n = len(lines) - 1
    check_lines(args.out, n, args.seeds)
    print(f"Wrote {n} runs to {args.out}")
    for b in BUDGETS:
        nts, total = totals[b]
        print(f"  {budget_tag(b)}: ACTUAL TOTAL_STEPS per run: {total}")
    print(f"  set --array=1-{n}%4")


if __name__ == "__main__":
    main()
