"""Generate the DR-ladder + LOO sweep JSONL, velocity-obs variant.

Same 10 configs as `gen_dr_ladder.py` (L0_none .. L5_full_obs, LOO_no_pos ..
LOO_no_env) -- imports its `_CONFIGS` directly so the DR-cluster -> config-key
mapping has ONE source of truth and cannot drift between the two sweeps. See
that script's docstring for the full cluster spec and the vault's
"Plan - Sim-to-Real Gap Protocol" for the research design.

What's DIFFERENT here, on every line:
  - `obs_include_velocity: true` -- appends arm joint velocity (6D) + finger
    velocity (1D) to the obs (26D -> 33D). See the vault's
    "Plan - Add Velocity": a single L1_pos test at this setting (action_scale
    =0.04, position DR only) converged within ~10M steps, well under the
    ladder's usual ~32M-step budget. This sweep tests whether that holds
    across the whole dose-response ladder, or was specific to the easiest
    rung.
  - `action_scale: 0.04` -- the value confirmed to match real-robot
    deployment (see run_gap_protocol.py's 2026-07-22 action_scale fix: the
    ORIGINAL DR-ladder policies were trained at 0.04 per their metadata.json,
    but the env's default_config() drifted to 0.015 afterward). Setting it
    explicitly here, on every line, avoids silently inheriting whatever the
    env default happens to be later -- the same reasoning gen_dr_ladder.py
    already applies to episode_length.

run_id / wandb_tags get a "_vel" / "velocity" marker so these runs are never
confused with the original (no-velocity) ladder in W&B or in
gap_protocol_policy_map.json.

episode_length=400 is inherited unchanged from gen_dr_ladder.py's _CONFIGS
loop below (same reasoning: ur3_pick.default_config()'s 250 is stale).
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))))

from batch_runs.sweeps.gen_dr_ladder import (  # noqa: E402
    _CONFIGS,
    EPISODE_LENGTH,
    WANDB_PROJECT,
)

ACTION_SCALE = 0.04

_HEADER = f"""\
# DR-ladder + LOO sweep, VELOCITY-OBS variant -- "Plan - Add Velocity"
# (VT2-SimToReal-Robotics). Generated by
# batch_runs/sweeps/gen_dr_ladder_velocity.py -- DO NOT hand-edit; regenerate
# instead. Same {len(_CONFIGS)} configs as gen_dr_ladder.py (imported directly,
# not re-specified -- single source of truth for the DR cluster mapping).
#
# Differs from the original ladder on every line: obs_include_velocity=true
# (26D obs -> 33D: + arm qvel(6) + finger qvel(1)) and action_scale=0.04
# (explicit, matching the value confirmed correct for real-robot deployment --
# see run_gap_protocol.py's action_scale fix). A single L1_pos pilot at this
# exact setting converged within ~10M steps (vs the ladder's usual ~32M) --
# this sweep checks whether that speedup holds across the whole dose-response
# ladder or was specific to the easiest rung (see the vault plan).
#
# {len(_CONFIGS)} configs x N seeds. Comment/blank lines are skipped by the
# runner and do NOT count toward the 1-based SLURM_ARRAY_TASK_ID.
"""


def build_lines(seeds):
    lines = [_HEADER]
    for config_id, overrides, tags in _CONFIGS:
        for seed in seeds:
            entry = {
                "env_name": "UR3Pick",
                "seed": int(seed),
                "run_id": f"{config_id}_vel_s{seed}",
                "wandb_project": WANDB_PROJECT,
                "video_every_evals": 6,
                "render_every": 1,
                "episode_length": EPISODE_LENGTH,
                "action_scale": ACTION_SCALE,
                "obs_include_velocity": True,
                **overrides,
                "wandb_tags": [*tags, "velocity", f"as{ACTION_SCALE}", f"s{seed}"],
            }
            lines.append(json.dumps(entry))
    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--out",
        default=os.path.join(
            os.path.dirname(__file__), "UR3Pick_dr_ladder_velocity.jsonl"
        ),
    )
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2])
    ap.add_argument(
        "--force", action="store_true", help="overwrite an existing file"
    )
    args = ap.parse_args()

    if os.path.exists(args.out) and not args.force:
        raise SystemExit(
            f"{args.out} already exists; pass --force to overwrite "
            f"(the file should be regenerated from this script, not hand-edited)"
        )

    lines = build_lines(args.seeds)
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    n_runs = len(_CONFIGS) * len(args.seeds)
    print(f"Wrote {n_runs} runs ({len(_CONFIGS)} configs x {len(args.seeds)} "
          f"seeds) to {args.out}")
    assert {c for c, _, _ in _CONFIGS} == {
        "L0_none", "L1_pos", "L2_pos_cube", "L3_pos_cube_robot", "L4_full",
        "L5_full_obs", "LOO_no_pos", "LOO_no_cube", "LOO_no_robot",
        "LOO_no_env",
    }, "config set drifted from gen_dr_ladder.py's 10 configs -- investigate"


if __name__ == "__main__":
    main()
