#!/usr/bin/env python3
"""Sweep B of campaign "Sweeps From What Worked" (Wave 1, row 2): DR dose from scratch.

Question: trained FROM SCRATCH (no warm start), where on the physics-DR ladder
does the defence PPO bundle stop saturating? 4 cells x 2 seeds = 8 runs.

Each cell is the direct from-scratch counterpart of a warm-started Curriculum v3
rung; comparison row (W&B, 2026-09-02, commit 38c8372, warm-started):
  Curr_v3_L1_pos_s0 0.648 / L2_pos_cube 0.652 / L3_pos_cube_robot 0.621 / L4_full 0.594.

Base of every line: the defence line Snappy2_as04_ar70_g01_s{seed} from
UR3Pick_snappy2.jsonl, built by gen_snappy2.build_entry (REUSED, not copied):
defence PPO anchor a1b0c1d1, action_scale 0.04, action_rate -0.7, gate g01,
gripper_action_scale 0.02, cube-mass DR [0.85, 1.15], 2pi cube yaw, mid pose
library. On top: the rung's override dict from gen_dr_ladder._CONFIGS (never
retyped), then lifter_tilt_max = gen_dr_ladder.LIFTER_TILT_MAX (0.12, the
ladder value; the defence run trained at 0.05), num_timesteps 30_000_000,
num_evals 32, num_eval_envs 256 (the v3 rung budget and eval geometry, so
curves compare eval-for-eval).

L1 note: L1_pos has an EMPTY override dict on purpose -- the baked env defaults
ARE position DR; the defence line's cube-mass DR stays on. So SweepB_L1_pos is
"the defence bundle at lifter_tilt_max 0.12 and 30 M steps", NOT identical to
Curr_v3_L1_pos (which had no cube-mass DR).

Cube-mass caveat for L2-L4: the v3 rungs only set cube_mass.enable and inherited
the env default range [0.7, 1.3]; these lines keep the defence pin 0.85/1.15 --
recorded, not changed (campaign guardrail: stay near what worked).
"""

from __future__ import annotations

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_satsweep as gs        # noqa: E402
import gen_rewardgate as rg      # noqa: E402
import gen_snappy as sn          # noqa: E402
import gen_snappy2 as sn2        # noqa: E402
import gen_dr_ladder as dl       # noqa: E402

CONFIG_IDS = ("L1_pos", "L2_pos_cube", "L3_pos_cube_robot", "L4_full")
ACTION_SCALE = 0.04
ACTION_RATE = -0.7
GATE_CELL = sn.GATE_CELL
NUM_TIMESTEPS = 30_000_000
NUM_EVALS = 32
NUM_EVAL_ENVS = 256
LIFTER_TILT_MAX = dl.LIFTER_TILT_MAX
CUBE_MASS_RANGE = (0.85, 1.15)
BASE_DR_KEYS = frozenset({"domain_rand.enable", "domain_rand.cube_mass.enable",
                           "domain_rand.cube_mass.min", "domain_rand.cube_mass.max"})
V3_COMPARISON = {"L1_pos": 0.648, "L2_pos_cube": 0.652,
                 "L3_pos_cube_robot": 0.621, "L4_full": 0.594}
REQUIRED_TAGS = ("sweepB", "scratch")


def ladder_cells():
    by_id = {cid: (o, tags) for cid, o, tags in dl._CONFIGS}
    missing = [c for c in CONFIG_IDS if c not in by_id]
    if missing:
        raise SystemExit(f"gen_dr_ladder._CONFIGS lacks {missing}; "
                         f"the ladder changed shape")
    cells = [(cid, dict(by_id[cid][0]), list(by_id[cid][1])) for cid in CONFIG_IDS]
    for cid, o, _ in cells:
        bad = [k for k in o if not k.startswith("domain_rand.")]
        assert not bad, (f"{cid}: non-DR override keys {bad} would leak into "
                         f"the line")
    return cells


def dr_keys():
    return {k for _, o, _ in ladder_cells() for k in o}


def config_id_of(run_id):
    return run_id[len("SweepB_"):].rsplit("_s", 1)[0]


def build_entry(config_id, overrides, tags, seed, shared):
    entry = sn2.build_entry(ACTION_SCALE, ACTION_RATE, seed, shared,
                            NUM_TIMESTEPS, NUM_EVALS)
    entry.update(overrides)
    entry["lifter_tilt_max"] = LIFTER_TILT_MAX
    entry["num_eval_envs"] = NUM_EVAL_ENVS
    entry["run_id"] = f"SweepB_{config_id}_s{seed}"
    entry["wandb_tags"] = [*REQUIRED_TAGS, *tags, f"s{seed}",
                           f"anchor{rg.ANCHOR_CELL}"]
    # re-insert so wandb_tags stays the last key, as in every sibling jsonl
    entry["wandb_tags"] = entry.pop("wandb_tags")
    return entry


def build_lines(seeds):
    nts, total = gs.solve_budget(NUM_TIMESTEPS, NUM_EVALS)
    shared = gs.load_target_config()
    pose_level, pose_n, pose_sha = gs.init_pose_library_fingerprint()
    assert ACTION_SCALE in sn2.ACTION_SCALES and ACTION_RATE in sn2.ACTION_RATES, (
        "the defence cell left the snappy2 grid")
    assert shared.get("action_scale") == ACTION_SCALE, (
        shared.get("action_scale"))
    assert (shared.get("domain_rand.cube_mass.min"),
            shared.get("domain_rand.cube_mass.max")) == CUBE_MASS_RANGE

    cells = ladder_cells()
    n_runs = len(cells) * len(seeds)
    header = (
        f"# Sweep B -- DR dose from scratch. Generated by\n"
        f"# batch_runs/sweeps/gen_sweep_dr_dose.py -- DO NOT hand-edit; "
        f"regenerate.\n"
        f"# Plan: 'Sweeps From What Worked' (Wave 1, row 2).\n"
        f"#\n"
        f"# Question: trained FROM SCRATCH (no warm start), where on the\n"
        f"# physics-DR ladder does the defence PPO bundle stop saturating?\n"
        f"#\n"
        f"# Cell table with Curr_v3 warm-started comparison (W&B 2026-09-02,\n"
        f"# commit 38c8372):\n"
        f"#   L1_pos              Curr_v3 0.648\n"
        f"#   L2_pos_cube         Curr_v3 0.652\n"
        f"#   L3_pos_cube_robot   Curr_v3 0.621\n"
        f"#   L4_full             Curr_v3 0.594\n"
        f"#\n"
        f"# Base-line provenance: Snappy2_as04_ar70_g01_s{{seed}} from\n"
        f"# UR3Pick_snappy2.jsonl, built by gen_snappy2.build_entry -- the\n"
        f"# defence PPO anchor a1b0c1d1, action_scale 0.04, action_rate -0.7,\n"
        f"# gate g01, gripper_action_scale 0.02, cube-mass DR [0.85, 1.15],\n"
        f"# 2pi cube yaw, mid pose library.\n"
        f"#\n"
        f"# L1 note: L1_pos has an EMPTY override dict on purpose -- the baked\n"
        f"# env defaults ARE position DR; the defence line's cube-mass DR stays\n"
        f"# on. So SweepB_L1_pos is 'the defence bundle at lifter_tilt_max 0.12\n"
        f"# and 30 M steps', NOT identical to Curr_v3_L1_pos (which had no\n"
        f"# cube-mass DR).\n"
        f"#\n"
        f"# Cube-mass caveat for L2-L4: the v3 rungs only set\n"
        f"# cube_mass.enable and inherited the env default range [0.7, 1.3];\n"
        f"# these lines keep the defence pin 0.85/1.15 -- recorded, not changed\n"
        f"# (campaign guardrail: stay near what worked).\n"
        f"#\n"
        f"# FROZEN: {rg.GATE_BOX_KEY}={sn.GATE_BOX}, "
        f"{rg.GATE_ALIGN_KEY}={sn.GATE_ALIGN} (cell {GATE_CELL});\n"
        f"#   gripper_action_scale={sn.GRIPPER_ACTION_SCALE:g},\n"
        f"#   action_scale, action_rate, PPO at anchor {rg.ANCHOR_CELL},\n"
        f"#   lifter_tilt_max={LIFTER_TILT_MAX}.\n"
        f"#\n"
        f"# Budget: num_timesteps={NUM_TIMESTEPS}, num_evals={NUM_EVALS}, "
        f"num_eval_envs={NUM_EVAL_ENVS},\n"
        f"# env_step_per_training_step={gs.env_step_per_training_step()}, "
        f"nts={nts} -> ACTUAL TOTAL_STEPS={total}.\n"
        f"# Identical to the Curriculum v3 rung budget (30,474,240).\n"
        f"#\n"
        f"# {len(cells)} cells x {len(seeds)} seed(s) = {n_runs} runs. "
        f"Comment/blank lines are skipped by\n"
        f"# run_one_ur3.py::load_config and do NOT consume a SLURM array "
        f"index: set --array=1-{n_runs}%4.\n"
        f"#\n"
        f"# INIT-POSE LIBRARY: level={pose_level!r} n_poses={pose_n} "
        f"sha256={pose_sha}\n"
        f"# MUST match the runs these are compared against."
    )

    lines = [header]
    for cid, overrides, tags in cells:
        for seed in seeds:
            lines.append(json.dumps(build_entry(cid, overrides, tags, seed,
                                                 shared)))
    return lines, total


def check_lines(path, expected_n, seeds):
    rows = [json.loads(l) for l in open(path, encoding="utf-8")
            if l.strip() and not l.lstrip().startswith("#")]
    assert len(rows) == expected_n, (f"{len(rows)} data lines, expected "
                                      f"{expected_n}")

    ids = [r["run_id"] for r in rows]
    assert len(set(ids)) == len(ids), f"duplicate run_id: {ids}"

    cells = {c: (o, tags) for c, o, tags in ladder_cells()}
    seen = set()
    for r in rows:
        rid = r["run_id"]
        config_id = config_id_of(rid)
        assert config_id in CONFIG_IDS, (f"{rid}: config_id {config_id} not in "
                                         f"CONFIG_IDS")
        assert rid.endswith(f"_s{r['seed']}"), rid
        assert r["entropy_cost"] == rg.ANCHOR["entropy_cost"], rid
        assert r["learning_rate"] == rg.ANCHOR["learning_rate"], rid
        assert r["reward_scaling"] == rg.ANCHOR["reward_scaling"], rid
        nf = r["network_factory"]
        assert tuple(nf["policy_hidden_layer_sizes"]) == (
            rg.ANCHOR["policy_hidden_layer_sizes"]), rid
        assert tuple(nf["value_hidden_layer_sizes"]) == (
            gs.VALUE_HIDDEN_LAYER_SIZES), rid
        assert r["box_z_rot_range"] == 6.283185307179586, rid
        assert r["episode_length"] == 400, rid
        assert r["obs_include_velocity"] is True, rid
        assert r["num_resets_per_eval"] == gs.NUM_RESETS_PER_EVAL, rid
        assert r["action_scale"] == ACTION_SCALE, rid
        assert r["action_rate"] == ACTION_RATE, rid
        assert r["gripper_action_scale"] == sn.GRIPPER_ACTION_SCALE, rid
        assert r[rg.GATE_BOX_KEY] is sn.GATE_BOX, rid
        assert r[rg.GATE_ALIGN_KEY] is sn.GATE_ALIGN, rid
        assert r["lifter_tilt_max"] == LIFTER_TILT_MAX, rid
        assert r["num_timesteps"] == NUM_TIMESTEPS, rid
        assert r["num_evals"] == NUM_EVALS, rid
        assert r["num_eval_envs"] == NUM_EVAL_ENVS, rid
        assert r["domain_rand.enable"] is True, rid
        assert r["domain_rand.cube_mass.enable"] is True, rid
        assert r["domain_rand.cube_mass.min"] == 0.85, rid
        assert r["domain_rand.cube_mass.max"] == 1.15, rid

        assert not (gs.REWARD_KEYS - {"action_rate"} & set(r)), rid

        dr_keys_on_row = {k for k in r if k.startswith("domain_rand.")}
        cell_override, cell_tags = cells[config_id]
        cell_dr_keys = {k for k in cell_override if k.startswith("domain_rand.")}
        expected_dr = BASE_DR_KEYS | cell_dr_keys

        assert dr_keys_on_row == expected_dr, (
            f"{rid}: DR key mismatch, got {dr_keys_on_row}, "
            f"expected {expected_dr}")

        for tag in REQUIRED_TAGS:
            assert tag in r["wandb_tags"], f"{rid} missing tag {tag}"
        for tag in cell_tags:
            assert tag in r["wandb_tags"], (
                f"{rid} missing tag {tag}")
        assert f"s{r['seed']}" in r["wandb_tags"], rid
        assert f"anchor{rg.ANCHOR_CELL}" in r["wandb_tags"], rid

        seen.add((config_id, r["seed"]))

    assert seen == {(c, s) for c in CONFIG_IDS for s in seeds}, (
        f"missing or extra (config_id, seed) pairs")

    varying = {"seed", "run_id", "wandb_tags"} | dr_keys()
    base = {k: v for k, v in rows[0].items() if k not in varying}
    for r in rows[1:]:
        other = {k: v for k, v in r.items() if k not in varying}
        assert other == base, (
            f"{r['run_id']} differs from {rows[0]['run_id']} outside varying "
            f"keys")

    return rows


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1])
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if os.path.exists(args.out) and not args.force:
        raise SystemExit(
            f"{args.out} already exists; pass --force to overwrite (this file "
            f"is generated, not hand-edited)")

    lines, total = build_lines(args.seeds)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    n = len(lines) - 1
    check_lines(args.out, n, args.seeds)
    print(f"Wrote {n} runs to {args.out}")
    for cid in CONFIG_IDS:
        print(f"  {cid}: Curr_v3 warm-started {V3_COMPARISON[cid]:.3f}")
    print(f"  ACTUAL TOTAL_STEPS per run: {total}")
    print(f"  set --array=1-{n}%4")


if __name__ == "__main__":
    main()
